-- function divide
DELIMITER //
CREATE FUNCTION SafeDiv( a INT, b INT)
RETURNS FLOAT
READS SQL DATA
BEGIN
	DECLARE res FLOAT;
	IF b = 0 THEN 
		SET res = 0;
	ELSE
		SET res = a / b;
	END IF;
	RETURN res;
END;//
DELIMITER ;